PRI-NaszSamochód/Controllers/WallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.DynamicData;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PRI_NaszSamochód.Models;

namespace PRI_NaszSamochód.Controllers
{   [Authorize]
    public class WallController : Controller
    {
       
        public ActionResult WallContent()
        {
            var db = ApplicationDbContext.Create();
            var currentUserId = User.Identity.GetUserId();
            var posts = (from p in db.Posts
                join friend in db.Friends on
                p.Creator equals friend.User2
                where friend.User1.Id == currentUserId 
                && friend.Status == FriendStatus.Friends
                orderby p.Id descending 
                select p
                
                ).Take(10).ToList();

            
            return View(new PostViewModelList(posts));
        }


        public ActionResult AddPostView()
        {
            return View();
        }
        [HttpPost]
        public void AddPost(PostModel post)
        {
            
           var db =  ApplicationDbContext.Create();
            post.Added = DateTime.Now;
            post.Creator = db.Users.Find(User.Identity.GetUserId());
            db.Posts.Add(post);
            db.SaveChanges();
            
        }


    }
}

PRI-NaszSamochód/Views/Wall/AddPostView.cshtml
@model PRI_NaszSamochód.Models.PostModel
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="~/Content/css/main.css">
    <link rel="stylesheet" href="~/Content/css/loginPage.css">
    <link rel="stylesheet" href="~/Content/css/wall.css">


    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



</head>

<body>
@using (Html.BeginForm("AddPost", "Wall", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
   
    @Html.AntiForgeryToken()

        <div class="flex-c">
            @Html.TextAreaFor(m => m.Text, new { @class="newPostContent"})
            <button type="submit" class="btn-success" value="AddPost" onclick="(function (){window.close();})">Dodaj Post</button>
        </div>
}
</body>

PRI-NaszSamochód/Views/Wall/WallContent.cshtml
@using PRI_NaszSamochód.Models
@model PostViewModelList


<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <script src="~/Content/node_modules/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/css/main.css">
    <link rel="stylesheet" href="~/Content/css/userPage.css" />
    <link rel="stylesheet" href="~/Content/css/wall.css" />
    @*@Scripts.Render("~/Content/js/custom/infiniteScroll.js")*@
    @Scripts.Render("~/Content/node_modules/jscroll/jquery.jscroll.min.js")


    <title>Profil użytkownika</title>
</head>

<body>
  

<div class="flex-add-button">
    <button type="submit" class="btn-success" value="AddPost" id="AddPost" onclick="AddPost()">Dodaj Post</button>
</div>
<div class="container-flex" id="scrollIt">
    <div class="wall-flex">
        @foreach (var post in Model.GetPostViewModels())
        {


            <div class="post" ng-controller="PostController" >
                <div class="postHeader" ng-click="PostClicked($event)" id="@post.Creator.Id">
                    <ul>
                        <li>
                            <div class="userProfilePhoto userProfilePhotoSmall" style="background-image:url(@post.CreatorPhoto)"></div></li>
                        <li>
                            <p>@post.Creator.Name  @post.Creator.Surname
                            <p></li>
                        <li>
                            <p></p></li>
                    </ul>
                </div>
                <div class="postContent">
                    <p class="postText">@post.Text</p>
                </div>
                <button class="btn-success btn-like">Poleć!</button>
            </div>
        }

    </div>

</div>
</body>


</html>


<script>
    function AddPost() {
        var page = "/Wall/AddPostView";

        var $dialog = $("<div class='newPostDialog'></div>")
            .html('<iframe scrolling="no" src="' + page +
            '" width="100%" height="100%"></iframe>').dialog({
                autoOpen: true,
                modal: true,
                width: 650,
                height: 350,
                title: "Dodaj Post",
                resizable: false
            });
        
    }
</script>

PRI-NaszSamochód/Views/Wall/WallHeader.cshtml
@using PRI_NaszSamochód.Models
@model GroupViewModel
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    @*JQuery*@
    <script src="~/Content/node_modules/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    @*Css*@
    <link rel="stylesheet" href="~/Content/css/main.css">
    <link rel="stylesheet" href="~/Content/css/userPage.css" />

    @*Awesome Fonts*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    @*Angular*@
    <script data-require="angular.js@1.5.10" data-semver="1.5.10" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.10/angular.min.js"></script>
    <script data-require="angular-router@1.2.0-rc1" data-semver="1.2.0-rc1" src="https://code.angularjs.org/1.2.0rc1/angular-route.js"></script>

    @*Dropzone*@
    <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">
    @Scripts.Render("~/Content/js/custom/dialogScript.js")
    @Scripts.Render("~/Content/js/lib/dropzone.js")

    <title>Profil użytkownika</title>
</head>

<body ng-app="myApp">

    <div class="container-flex">
        <h1 style="color: white">Wall Header - in progress</h1>
    </div>
</body>

</html>